#!/bin/bash

set -e

if [ ! -f Coco.jar ]; then
  wget http://www.ssw.uni-linz.ac.at/Coco/Java/Coco.jar -O Coco.jar
fi

java -jar Coco.jar src/main/java/org/hummingbirdlang/parser/Syntax.atg

files="src/main/java/org/hummingbirdlang/parser/Parser.java
       src/main/java/org/hummingbirdlang/parser/Scanner.java"

for f in $files; do
  sed -i "" "s/[ \t]*$//" "$f"
done
